#!/usr/bin/ruby

require_relative 'lib/rbshell.rb'
require 'readline'
require 'socket'
require 'etc'

shell = RbShell.new(File.join(__dir__, File.basename(__FILE__)))

#Should somehow use the completion profile from irb... that would be nice
Readline.completion_proc = proc {|s| RbShell::Command.instance_methods(false).filter {|m| m.start_with? s}}

while buf = Readline.readline(Etc.getlogin + "@" + Socket.gethostname + ":" + Dir.pwd + "$ ", true)
  begin
    if !buf.empty?
      r = shell.run(buf)
      if r != nil
        #Explicit call to .to_s for array...
        puts (r.to_s)
      end
    end
  rescue Exception => e
    p "invalid command: " + e.to_s
  end

end
