#!/usr/bin/ruby

require_relative 'lib/rbshell.rb'
require 'readline'
require 'socket'
require 'etc'

shell = RbShell::Shell.new

Readline.completion_proc = proc {|s| RbShell::Shell::Command.instance_methods(false).filter {|m| m.start_with? s}}

while buf = Readline.readline(Etc.getlogin + "@" + Socket.gethostname + ":" + Dir.pwd + "$ ", true)
  begin
    if !buf.empty?
      r = shell.run(buf)
      if r != nil
        pp r
      end
    end
  rescue Exception => e
    p "invalid command: " + e.to_s
  end

end
